bugfix: Symbol doesn't have sub method in ruby 1.9
../vimup/vimup:292:in `block in usage': undefined method `sub' for :subcommand_new_script:Symbol (NoMethodError)